### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by lxfu1** [lahmatiy/react-render-tracker#13] opened 2021-09-13 10:55 UTC
Refer to "Option 1 – Using with browser's devtools" and can't get expected result.

![image](https://user-images.githubusercontent.com/31396322/133071742-12cb00f8-b063-46ca-9b87-351d98bd0c2c.png)

**Comment by lahmatiy** [comment] 2021-09-13 20:15
@lxfu1 Make sure the following conditions are met:
- a `<script>` with correct url to `react-render-tracker.js` is injected to the page (its HTML)
- check on the Network tab in devtools, if this script is downloading with no errors (may to be rejected for some reasons)
- a page with injected `<script>` is not in a `<iframe>`
- there are no CSP related error on console
- there are no any other error related to the `react-render-tracker.js`

**Comment by lahmatiy** [comment] 2021-09-24 00:03
There were some issues that may caused such a problem. Please, try latest [version 0.4](https://github.com/lahmatiy/react-render-tracker/releases/tag/v0.4.0) which just published. I rewrite readme, now it also has an option to open UI right in the page  (`Option #0` in the readme). You can try it if option 1 is still not working for you.
I'm closing the issue since no additional details or comments on the issue. Feel free to reopen it if the problem is still here.

**Closed by lahmatiy** 2021-09-24 00:03 UTC
